//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PedidosExpressEntities : DbContext
    {
        public PedidosExpressEntities()
            : base("name=PedidosExpressEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Direccion> Direccion { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Geo> Geo { get; set; }
        public virtual DbSet<LineaPedido> LineaPedido { get; set; }
        public virtual DbSet<MecanismoContacto> MecanismoContacto { get; set; }
        public virtual DbSet<Party> Party { get; set; }
        public virtual DbSet<Pedido> Pedido { get; set; }
        public virtual DbSet<Plato> Plato { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoDireccion> TipoDireccion { get; set; }
        public virtual DbSet<TipoMecanismo> TipoMecanismo { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<v_Cliente> v_Cliente { get; set; }
        public virtual DbSet<v_Direccion> v_Direccion { get; set; }
        public virtual DbSet<v_Estado> v_Estado { get; set; }
        public virtual DbSet<v_Geo> v_Geo { get; set; }
        public virtual DbSet<v_MecanismoContacto> v_MecanismoContacto { get; set; }
        public virtual DbSet<v_Party> v_Party { get; set; }
        public virtual DbSet<v_Pedido> v_Pedido { get; set; }
        public virtual DbSet<v_Platos> v_Platos { get; set; }
        public virtual DbSet<v_TIpoDireccion> v_TIpoDireccion { get; set; }
        public virtual DbSet<v_TipoMecanismo> v_TipoMecanismo { get; set; }
        public virtual DbSet<v_TipoUsuario> v_TipoUsuario { get; set; }
        public virtual DbSet<v_Usuario> v_Usuario { get; set; }
    
        [DbFunction("PedidosExpressEntities", "f_buscarClienteID")]
        public virtual IQueryable<f_buscarClienteID_Result> f_buscarClienteID(string partyID)
        {
            var partyIDParameter = partyID != null ?
                new ObjectParameter("PartyID", partyID) :
                new ObjectParameter("PartyID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_buscarClienteID_Result>("[PedidosExpressEntities].[f_buscarClienteID](@PartyID)", partyIDParameter);
        }
    
        [DbFunction("PedidosExpressEntities", "f_buscarClienteNombre")]
        public virtual IQueryable<f_buscarClienteNombre_Result> f_buscarClienteNombre(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_buscarClienteNombre_Result>("[PedidosExpressEntities].[f_buscarClienteNombre](@Nombre)", nombreParameter);
        }
    
        [DbFunction("PedidosExpressEntities", "f_buscarPlatoID")]
        public virtual IQueryable<f_buscarPlatoID_Result> f_buscarPlatoID(Nullable<int> platoID)
        {
            var platoIDParameter = platoID.HasValue ?
                new ObjectParameter("PlatoID", platoID) :
                new ObjectParameter("PlatoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_buscarPlatoID_Result>("[PedidosExpressEntities].[f_buscarPlatoID](@PlatoID)", platoIDParameter);
        }
    
        [DbFunction("PedidosExpressEntities", "f_buscarPlatoNombre")]
        public virtual IQueryable<f_buscarPlatoNombre_Result> f_buscarPlatoNombre(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_buscarPlatoNombre_Result>("[PedidosExpressEntities].[f_buscarPlatoNombre](@Nombre)", nombreParameter);
        }
    
        [DbFunction("PedidosExpressEntities", "f_buscarUsuarioID")]
        public virtual IQueryable<f_buscarUsuarioID_Result> f_buscarUsuarioID(string partyID)
        {
            var partyIDParameter = partyID != null ?
                new ObjectParameter("PartyID", partyID) :
                new ObjectParameter("PartyID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_buscarUsuarioID_Result>("[PedidosExpressEntities].[f_buscarUsuarioID](@PartyID)", partyIDParameter);
        }
    
        [DbFunction("PedidosExpressEntities", "f_buscarUsuarioNombre")]
        public virtual IQueryable<f_buscarUsuarioNombre_Result> f_buscarUsuarioNombre(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_buscarUsuarioNombre_Result>("[PedidosExpressEntities].[f_buscarUsuarioNombre](@Nombre)", nombreParameter);
        }
    
        [DbFunction("PedidosExpressEntities", "f_LineasPedido")]
        public virtual IQueryable<f_LineasPedido_Result> f_LineasPedido(Nullable<int> pedidoID)
        {
            var pedidoIDParameter = pedidoID.HasValue ?
                new ObjectParameter("PedidoID", pedidoID) :
                new ObjectParameter("PedidoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_LineasPedido_Result>("[PedidosExpressEntities].[f_LineasPedido](@PedidoID)", pedidoIDParameter);
        }
    
        [DbFunction("PedidosExpressEntities", "f_mostrarClientes")]
        public virtual IQueryable<f_mostrarClientes_Result> f_mostrarClientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_mostrarClientes_Result>("[PedidosExpressEntities].[f_mostrarClientes]()");
        }
    
        [DbFunction("PedidosExpressEntities", "f_MostrarPedidos")]
        public virtual IQueryable<f_MostrarPedidos_Result> f_MostrarPedidos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_MostrarPedidos_Result>("[PedidosExpressEntities].[f_MostrarPedidos]()");
        }
    
        [DbFunction("PedidosExpressEntities", "f_mostrarUsuarios")]
        public virtual IQueryable<f_mostrarUsuarios_Result> f_mostrarUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_mostrarUsuarios_Result>("[PedidosExpressEntities].[f_mostrarUsuarios]()");
        }
    
        [DbFunction("PedidosExpressEntities", "f_pedido_Fecha_Cliente")]
        public virtual IQueryable<f_pedido_Fecha_Cliente_Result> f_pedido_Fecha_Cliente(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFinal, string nombre)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_pedido_Fecha_Cliente_Result>("[PedidosExpressEntities].[f_pedido_Fecha_Cliente](@FechaInicio, @FechaFinal, @Nombre)", fechaInicioParameter, fechaFinalParameter, nombreParameter);
        }
    
        [DbFunction("PedidosExpressEntities", "f_pedidoCliente")]
        public virtual IQueryable<f_pedidoCliente_Result> f_pedidoCliente(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_pedidoCliente_Result>("[PedidosExpressEntities].[f_pedidoCliente](@Nombre)", nombreParameter);
        }
    
        [DbFunction("PedidosExpressEntities", "f_pedidoEstado")]
        public virtual IQueryable<f_pedidoEstado_Result> f_pedidoEstado(Nullable<int> estado)
        {
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_pedidoEstado_Result>("[PedidosExpressEntities].[f_pedidoEstado](@Estado)", estadoParameter);
        }
    
        [DbFunction("PedidosExpressEntities", "f_pedidoEstado_Cliente")]
        public virtual IQueryable<f_pedidoEstado_Cliente_Result> f_pedidoEstado_Cliente(Nullable<int> estado, string nombre)
        {
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_pedidoEstado_Cliente_Result>("[PedidosExpressEntities].[f_pedidoEstado_Cliente](@Estado, @Nombre)", estadoParameter, nombreParameter);
        }
    
        [DbFunction("PedidosExpressEntities", "f_pedidoEstado_Cliente_Fecha")]
        public virtual IQueryable<f_pedidoEstado_Cliente_Fecha_Result> f_pedidoEstado_Cliente_Fecha(Nullable<int> estado, string nombre, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFinal)
        {
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_pedidoEstado_Cliente_Fecha_Result>("[PedidosExpressEntities].[f_pedidoEstado_Cliente_Fecha](@Estado, @Nombre, @FechaInicio, @FechaFinal)", estadoParameter, nombreParameter, fechaInicioParameter, fechaFinalParameter);
        }
    
        [DbFunction("PedidosExpressEntities", "f_pedidoEstado_Fecha")]
        public virtual IQueryable<f_pedidoEstado_Fecha_Result> f_pedidoEstado_Fecha(Nullable<int> estado, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFinal)
        {
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_pedidoEstado_Fecha_Result>("[PedidosExpressEntities].[f_pedidoEstado_Fecha](@Estado, @FechaInicio, @FechaFinal)", estadoParameter, fechaInicioParameter, fechaFinalParameter);
        }
    
        [DbFunction("PedidosExpressEntities", "f_pedidoFecha")]
        public virtual IQueryable<f_pedidoFecha_Result> f_pedidoFecha(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFinal)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_pedidoFecha_Result>("[PedidosExpressEntities].[f_pedidoFecha](@FechaInicio, @FechaFinal)", fechaInicioParameter, fechaFinalParameter);
        }
    
        [DbFunction("PedidosExpressEntities", "f_pedidosActivos")]
        public virtual IQueryable<f_pedidosActivos_Result> f_pedidosActivos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_pedidosActivos_Result>("[PedidosExpressEntities].[f_pedidosActivos]()");
        }
    
        [DbFunction("PedidosExpressEntities", "f_UltimoEstado")]
        public virtual IQueryable<f_UltimoEstado_Result> f_UltimoEstado(Nullable<int> pedidoID)
        {
            var pedidoIDParameter = pedidoID.HasValue ?
                new ObjectParameter("PedidoID", pedidoID) :
                new ObjectParameter("PedidoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_UltimoEstado_Result>("[PedidosExpressEntities].[f_UltimoEstado](@PedidoID)", pedidoIDParameter);
        }
    
        public virtual int p_agregarCliente(string partyIDR, string primerNombreR, string segundoNombreR, string apellido1R, string apellido2R, string contraseñaR, string valorMecanismoR, Nullable<short> tipoMecanismoIDR, Nullable<bool> habilitado, Nullable<short> geoID, string lineaDireccion1, string lineaDireccion2, string lineaDireccion3, string instrucciones, Nullable<byte> tipoDireccionID)
        {
            var partyIDRParameter = partyIDR != null ?
                new ObjectParameter("PartyIDR", partyIDR) :
                new ObjectParameter("PartyIDR", typeof(string));
    
            var primerNombreRParameter = primerNombreR != null ?
                new ObjectParameter("PrimerNombreR", primerNombreR) :
                new ObjectParameter("PrimerNombreR", typeof(string));
    
            var segundoNombreRParameter = segundoNombreR != null ?
                new ObjectParameter("SegundoNombreR", segundoNombreR) :
                new ObjectParameter("SegundoNombreR", typeof(string));
    
            var apellido1RParameter = apellido1R != null ?
                new ObjectParameter("Apellido1R", apellido1R) :
                new ObjectParameter("Apellido1R", typeof(string));
    
            var apellido2RParameter = apellido2R != null ?
                new ObjectParameter("Apellido2R", apellido2R) :
                new ObjectParameter("Apellido2R", typeof(string));
    
            var contraseñaRParameter = contraseñaR != null ?
                new ObjectParameter("ContraseñaR", contraseñaR) :
                new ObjectParameter("ContraseñaR", typeof(string));
    
            var valorMecanismoRParameter = valorMecanismoR != null ?
                new ObjectParameter("ValorMecanismoR", valorMecanismoR) :
                new ObjectParameter("ValorMecanismoR", typeof(string));
    
            var tipoMecanismoIDRParameter = tipoMecanismoIDR.HasValue ?
                new ObjectParameter("TipoMecanismoIDR", tipoMecanismoIDR) :
                new ObjectParameter("TipoMecanismoIDR", typeof(short));
    
            var habilitadoParameter = habilitado.HasValue ?
                new ObjectParameter("Habilitado", habilitado) :
                new ObjectParameter("Habilitado", typeof(bool));
    
            var geoIDParameter = geoID.HasValue ?
                new ObjectParameter("GeoID", geoID) :
                new ObjectParameter("GeoID", typeof(short));
    
            var lineaDireccion1Parameter = lineaDireccion1 != null ?
                new ObjectParameter("LineaDireccion1", lineaDireccion1) :
                new ObjectParameter("LineaDireccion1", typeof(string));
    
            var lineaDireccion2Parameter = lineaDireccion2 != null ?
                new ObjectParameter("LineaDireccion2", lineaDireccion2) :
                new ObjectParameter("LineaDireccion2", typeof(string));
    
            var lineaDireccion3Parameter = lineaDireccion3 != null ?
                new ObjectParameter("LineaDireccion3", lineaDireccion3) :
                new ObjectParameter("LineaDireccion3", typeof(string));
    
            var instruccionesParameter = instrucciones != null ?
                new ObjectParameter("Instrucciones", instrucciones) :
                new ObjectParameter("Instrucciones", typeof(string));
    
            var tipoDireccionIDParameter = tipoDireccionID.HasValue ?
                new ObjectParameter("TipoDireccionID", tipoDireccionID) :
                new ObjectParameter("TipoDireccionID", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_agregarCliente", partyIDRParameter, primerNombreRParameter, segundoNombreRParameter, apellido1RParameter, apellido2RParameter, contraseñaRParameter, valorMecanismoRParameter, tipoMecanismoIDRParameter, habilitadoParameter, geoIDParameter, lineaDireccion1Parameter, lineaDireccion2Parameter, lineaDireccion3Parameter, instruccionesParameter, tipoDireccionIDParameter);
        }
    
        public virtual int p_agregarDireccion(Nullable<short> geoID, string lineaDireccion1, string lineaDireccion2, string lineaDireccion3, string instrucciones, Nullable<byte> tipoDireccionID, string partyID)
        {
            var geoIDParameter = geoID.HasValue ?
                new ObjectParameter("GeoID", geoID) :
                new ObjectParameter("GeoID", typeof(short));
    
            var lineaDireccion1Parameter = lineaDireccion1 != null ?
                new ObjectParameter("LineaDireccion1", lineaDireccion1) :
                new ObjectParameter("LineaDireccion1", typeof(string));
    
            var lineaDireccion2Parameter = lineaDireccion2 != null ?
                new ObjectParameter("LineaDireccion2", lineaDireccion2) :
                new ObjectParameter("LineaDireccion2", typeof(string));
    
            var lineaDireccion3Parameter = lineaDireccion3 != null ?
                new ObjectParameter("LineaDireccion3", lineaDireccion3) :
                new ObjectParameter("LineaDireccion3", typeof(string));
    
            var instruccionesParameter = instrucciones != null ?
                new ObjectParameter("Instrucciones", instrucciones) :
                new ObjectParameter("Instrucciones", typeof(string));
    
            var tipoDireccionIDParameter = tipoDireccionID.HasValue ?
                new ObjectParameter("TipoDireccionID", tipoDireccionID) :
                new ObjectParameter("TipoDireccionID", typeof(byte));
    
            var partyIDParameter = partyID != null ?
                new ObjectParameter("PartyID", partyID) :
                new ObjectParameter("PartyID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_agregarDireccion", geoIDParameter, lineaDireccion1Parameter, lineaDireccion2Parameter, lineaDireccion3Parameter, instruccionesParameter, tipoDireccionIDParameter, partyIDParameter);
        }
    
        public virtual int p_agregarMecanismo(string valorMecanismo, Nullable<short> tipoMecanismoID, string partyID)
        {
            var valorMecanismoParameter = valorMecanismo != null ?
                new ObjectParameter("ValorMecanismo", valorMecanismo) :
                new ObjectParameter("ValorMecanismo", typeof(string));
    
            var tipoMecanismoIDParameter = tipoMecanismoID.HasValue ?
                new ObjectParameter("TipoMecanismoID", tipoMecanismoID) :
                new ObjectParameter("TipoMecanismoID", typeof(short));
    
            var partyIDParameter = partyID != null ?
                new ObjectParameter("PartyID", partyID) :
                new ObjectParameter("PartyID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_agregarMecanismo", valorMecanismoParameter, tipoMecanismoIDParameter, partyIDParameter);
        }
    
        public virtual int p_agregarParty(string primerNombre, string segundoNombre, string apellido1, string apellido2, string contraseña, string partyID)
        {
            var primerNombreParameter = primerNombre != null ?
                new ObjectParameter("PrimerNombre", primerNombre) :
                new ObjectParameter("PrimerNombre", typeof(string));
    
            var segundoNombreParameter = segundoNombre != null ?
                new ObjectParameter("SegundoNombre", segundoNombre) :
                new ObjectParameter("SegundoNombre", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("Apellido1", apellido1) :
                new ObjectParameter("Apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("Apellido2", apellido2) :
                new ObjectParameter("Apellido2", typeof(string));
    
            var contraseñaParameter = contraseña != null ?
                new ObjectParameter("Contraseña", contraseña) :
                new ObjectParameter("Contraseña", typeof(string));
    
            var partyIDParameter = partyID != null ?
                new ObjectParameter("PartyID", partyID) :
                new ObjectParameter("PartyID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_agregarParty", primerNombreParameter, segundoNombreParameter, apellido1Parameter, apellido2Parameter, contraseñaParameter, partyIDParameter);
        }
    
        public virtual int p_agregarPlato(string nombre, string descripcion, Nullable<decimal> precio, byte[] fotografia, Nullable<bool> habilitadoSN)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(decimal));
    
            var fotografiaParameter = fotografia != null ?
                new ObjectParameter("Fotografia", fotografia) :
                new ObjectParameter("Fotografia", typeof(byte[]));
    
            var habilitadoSNParameter = habilitadoSN.HasValue ?
                new ObjectParameter("HabilitadoSN", habilitadoSN) :
                new ObjectParameter("HabilitadoSN", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_agregarPlato", nombreParameter, descripcionParameter, precioParameter, fotografiaParameter, habilitadoSNParameter);
        }
    
        public virtual int p_agregarUsuario(string partyID, Nullable<byte> tipoID)
        {
            var partyIDParameter = partyID != null ?
                new ObjectParameter("PartyID", partyID) :
                new ObjectParameter("PartyID", typeof(string));
    
            var tipoIDParameter = tipoID.HasValue ?
                new ObjectParameter("TipoID", tipoID) :
                new ObjectParameter("TipoID", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_agregarUsuario", partyIDParameter, tipoIDParameter);
        }
    
        public virtual int p_agregarUsuarioAdmin(string primerNombreR, string segundoNombreR, string apellido1R, string apellido2R, string contraseñaR, string valorMecanismoR, Nullable<short> tipoMecanismoIDR, string partyIDR, Nullable<short> geoID, string lineaDireccion1, string lineaDireccion2, string lineaDireccion3, string instrucciones, Nullable<byte> tipoDireccionID)
        {
            var primerNombreRParameter = primerNombreR != null ?
                new ObjectParameter("PrimerNombreR", primerNombreR) :
                new ObjectParameter("PrimerNombreR", typeof(string));
    
            var segundoNombreRParameter = segundoNombreR != null ?
                new ObjectParameter("SegundoNombreR", segundoNombreR) :
                new ObjectParameter("SegundoNombreR", typeof(string));
    
            var apellido1RParameter = apellido1R != null ?
                new ObjectParameter("Apellido1R", apellido1R) :
                new ObjectParameter("Apellido1R", typeof(string));
    
            var apellido2RParameter = apellido2R != null ?
                new ObjectParameter("Apellido2R", apellido2R) :
                new ObjectParameter("Apellido2R", typeof(string));
    
            var contraseñaRParameter = contraseñaR != null ?
                new ObjectParameter("ContraseñaR", contraseñaR) :
                new ObjectParameter("ContraseñaR", typeof(string));
    
            var valorMecanismoRParameter = valorMecanismoR != null ?
                new ObjectParameter("ValorMecanismoR", valorMecanismoR) :
                new ObjectParameter("ValorMecanismoR", typeof(string));
    
            var tipoMecanismoIDRParameter = tipoMecanismoIDR.HasValue ?
                new ObjectParameter("TipoMecanismoIDR", tipoMecanismoIDR) :
                new ObjectParameter("TipoMecanismoIDR", typeof(short));
    
            var partyIDRParameter = partyIDR != null ?
                new ObjectParameter("PartyIDR", partyIDR) :
                new ObjectParameter("PartyIDR", typeof(string));
    
            var geoIDParameter = geoID.HasValue ?
                new ObjectParameter("GeoID", geoID) :
                new ObjectParameter("GeoID", typeof(short));
    
            var lineaDireccion1Parameter = lineaDireccion1 != null ?
                new ObjectParameter("LineaDireccion1", lineaDireccion1) :
                new ObjectParameter("LineaDireccion1", typeof(string));
    
            var lineaDireccion2Parameter = lineaDireccion2 != null ?
                new ObjectParameter("LineaDireccion2", lineaDireccion2) :
                new ObjectParameter("LineaDireccion2", typeof(string));
    
            var lineaDireccion3Parameter = lineaDireccion3 != null ?
                new ObjectParameter("LineaDireccion3", lineaDireccion3) :
                new ObjectParameter("LineaDireccion3", typeof(string));
    
            var instruccionesParameter = instrucciones != null ?
                new ObjectParameter("Instrucciones", instrucciones) :
                new ObjectParameter("Instrucciones", typeof(string));
    
            var tipoDireccionIDParameter = tipoDireccionID.HasValue ?
                new ObjectParameter("TipoDireccionID", tipoDireccionID) :
                new ObjectParameter("TipoDireccionID", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_agregarUsuarioAdmin", primerNombreRParameter, segundoNombreRParameter, apellido1RParameter, apellido2RParameter, contraseñaRParameter, valorMecanismoRParameter, tipoMecanismoIDRParameter, partyIDRParameter, geoIDParameter, lineaDireccion1Parameter, lineaDireccion2Parameter, lineaDireccion3Parameter, instruccionesParameter, tipoDireccionIDParameter);
        }
    
        public virtual int p_agregarUsuarioCocina(string primerNombreR, string segundoNombreR, string apellido1R, string apellido2R, string contraseñaR, string valorMecanismoR, Nullable<short> tipoMecanismoIDR, string partyIDR, Nullable<short> geoID, string lineaDireccion1, string lineaDireccion2, string lineaDireccion3, string instrucciones, Nullable<byte> tipoDireccionID)
        {
            var primerNombreRParameter = primerNombreR != null ?
                new ObjectParameter("PrimerNombreR", primerNombreR) :
                new ObjectParameter("PrimerNombreR", typeof(string));
    
            var segundoNombreRParameter = segundoNombreR != null ?
                new ObjectParameter("SegundoNombreR", segundoNombreR) :
                new ObjectParameter("SegundoNombreR", typeof(string));
    
            var apellido1RParameter = apellido1R != null ?
                new ObjectParameter("Apellido1R", apellido1R) :
                new ObjectParameter("Apellido1R", typeof(string));
    
            var apellido2RParameter = apellido2R != null ?
                new ObjectParameter("Apellido2R", apellido2R) :
                new ObjectParameter("Apellido2R", typeof(string));
    
            var contraseñaRParameter = contraseñaR != null ?
                new ObjectParameter("ContraseñaR", contraseñaR) :
                new ObjectParameter("ContraseñaR", typeof(string));
    
            var valorMecanismoRParameter = valorMecanismoR != null ?
                new ObjectParameter("ValorMecanismoR", valorMecanismoR) :
                new ObjectParameter("ValorMecanismoR", typeof(string));
    
            var tipoMecanismoIDRParameter = tipoMecanismoIDR.HasValue ?
                new ObjectParameter("TipoMecanismoIDR", tipoMecanismoIDR) :
                new ObjectParameter("TipoMecanismoIDR", typeof(short));
    
            var partyIDRParameter = partyIDR != null ?
                new ObjectParameter("PartyIDR", partyIDR) :
                new ObjectParameter("PartyIDR", typeof(string));
    
            var geoIDParameter = geoID.HasValue ?
                new ObjectParameter("GeoID", geoID) :
                new ObjectParameter("GeoID", typeof(short));
    
            var lineaDireccion1Parameter = lineaDireccion1 != null ?
                new ObjectParameter("LineaDireccion1", lineaDireccion1) :
                new ObjectParameter("LineaDireccion1", typeof(string));
    
            var lineaDireccion2Parameter = lineaDireccion2 != null ?
                new ObjectParameter("LineaDireccion2", lineaDireccion2) :
                new ObjectParameter("LineaDireccion2", typeof(string));
    
            var lineaDireccion3Parameter = lineaDireccion3 != null ?
                new ObjectParameter("LineaDireccion3", lineaDireccion3) :
                new ObjectParameter("LineaDireccion3", typeof(string));
    
            var instruccionesParameter = instrucciones != null ?
                new ObjectParameter("Instrucciones", instrucciones) :
                new ObjectParameter("Instrucciones", typeof(string));
    
            var tipoDireccionIDParameter = tipoDireccionID.HasValue ?
                new ObjectParameter("TipoDireccionID", tipoDireccionID) :
                new ObjectParameter("TipoDireccionID", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_agregarUsuarioCocina", primerNombreRParameter, segundoNombreRParameter, apellido1RParameter, apellido2RParameter, contraseñaRParameter, valorMecanismoRParameter, tipoMecanismoIDRParameter, partyIDRParameter, geoIDParameter, lineaDireccion1Parameter, lineaDireccion2Parameter, lineaDireccion3Parameter, instruccionesParameter, tipoDireccionIDParameter);
        }
    
        public virtual int p_BloquearCliente(Nullable<bool> habilitado, string partyID)
        {
            var habilitadoParameter = habilitado.HasValue ?
                new ObjectParameter("Habilitado", habilitado) :
                new ObjectParameter("Habilitado", typeof(bool));
    
            var partyIDParameter = partyID != null ?
                new ObjectParameter("PartyID", partyID) :
                new ObjectParameter("PartyID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_BloquearCliente", habilitadoParameter, partyIDParameter);
        }
    
        public virtual int p_cambiarContraseña(string partyID, string nuevaContraseña)
        {
            var partyIDParameter = partyID != null ?
                new ObjectParameter("PartyID", partyID) :
                new ObjectParameter("PartyID", typeof(string));
    
            var nuevaContraseñaParameter = nuevaContraseña != null ?
                new ObjectParameter("NuevaContraseña", nuevaContraseña) :
                new ObjectParameter("NuevaContraseña", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_cambiarContraseña", partyIDParameter, nuevaContraseñaParameter);
        }
    
        public virtual int p_CambiarEstadoPedido(Nullable<byte> estadoID, Nullable<int> pedidoID)
        {
            var estadoIDParameter = estadoID.HasValue ?
                new ObjectParameter("EstadoID", estadoID) :
                new ObjectParameter("EstadoID", typeof(byte));
    
            var pedidoIDParameter = pedidoID.HasValue ?
                new ObjectParameter("PedidoID", pedidoID) :
                new ObjectParameter("PedidoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_CambiarEstadoPedido", estadoIDParameter, pedidoIDParameter);
        }
    
        public virtual int p_EliminarPedido(Nullable<int> pedidoID, ObjectParameter retorno)
        {
            var pedidoIDParameter = pedidoID.HasValue ?
                new ObjectParameter("PedidoID", pedidoID) :
                new ObjectParameter("PedidoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_EliminarPedido", pedidoIDParameter, retorno);
        }
    
        public virtual int p_EliminarPedidosRegistro(Nullable<int> pedidoID, ObjectParameter retorno)
        {
            var pedidoIDParameter = pedidoID.HasValue ?
                new ObjectParameter("PedidoID", pedidoID) :
                new ObjectParameter("PedidoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_EliminarPedidosRegistro", pedidoIDParameter, retorno);
        }
    
        public virtual int p_EliminarPlato(Nullable<int> platoID, ObjectParameter retorno)
        {
            var platoIDParameter = platoID.HasValue ?
                new ObjectParameter("PlatoID", platoID) :
                new ObjectParameter("PlatoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_EliminarPlato", platoIDParameter, retorno);
        }
    
        public virtual int p_EliminarUsuario(string partyID)
        {
            var partyIDParameter = partyID != null ?
                new ObjectParameter("PartyID", partyID) :
                new ObjectParameter("PartyID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_EliminarUsuario", partyIDParameter);
        }
    
        public virtual int p_HabilitarPlato(Nullable<bool> habilitado, Nullable<int> platoID)
        {
            var habilitadoParameter = habilitado.HasValue ?
                new ObjectParameter("Habilitado", habilitado) :
                new ObjectParameter("Habilitado", typeof(bool));
    
            var platoIDParameter = platoID.HasValue ?
                new ObjectParameter("PlatoID", platoID) :
                new ObjectParameter("PlatoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_HabilitarPlato", habilitadoParameter, platoIDParameter);
        }
    
        public virtual int p_modificarDireccion(Nullable<byte> direccionID, Nullable<short> geoID, string lineaDireccion1, string lineaDireccion2, string lineaDireccion3, string instrucciones, Nullable<byte> tipoDireccionID, string partyID)
        {
            var direccionIDParameter = direccionID.HasValue ?
                new ObjectParameter("DireccionID", direccionID) :
                new ObjectParameter("DireccionID", typeof(byte));
    
            var geoIDParameter = geoID.HasValue ?
                new ObjectParameter("GeoID", geoID) :
                new ObjectParameter("GeoID", typeof(short));
    
            var lineaDireccion1Parameter = lineaDireccion1 != null ?
                new ObjectParameter("LineaDireccion1", lineaDireccion1) :
                new ObjectParameter("LineaDireccion1", typeof(string));
    
            var lineaDireccion2Parameter = lineaDireccion2 != null ?
                new ObjectParameter("LineaDireccion2", lineaDireccion2) :
                new ObjectParameter("LineaDireccion2", typeof(string));
    
            var lineaDireccion3Parameter = lineaDireccion3 != null ?
                new ObjectParameter("LineaDireccion3", lineaDireccion3) :
                new ObjectParameter("LineaDireccion3", typeof(string));
    
            var instruccionesParameter = instrucciones != null ?
                new ObjectParameter("Instrucciones", instrucciones) :
                new ObjectParameter("Instrucciones", typeof(string));
    
            var tipoDireccionIDParameter = tipoDireccionID.HasValue ?
                new ObjectParameter("TipoDireccionID", tipoDireccionID) :
                new ObjectParameter("TipoDireccionID", typeof(byte));
    
            var partyIDParameter = partyID != null ?
                new ObjectParameter("PartyID", partyID) :
                new ObjectParameter("PartyID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_modificarDireccion", direccionIDParameter, geoIDParameter, lineaDireccion1Parameter, lineaDireccion2Parameter, lineaDireccion3Parameter, instruccionesParameter, tipoDireccionIDParameter, partyIDParameter);
        }
    
        public virtual int p_modificarMecanismo(string valorMecanismo, Nullable<short> tipoMecanismoID, Nullable<short> mecanismoID, string partyID)
        {
            var valorMecanismoParameter = valorMecanismo != null ?
                new ObjectParameter("ValorMecanismo", valorMecanismo) :
                new ObjectParameter("ValorMecanismo", typeof(string));
    
            var tipoMecanismoIDParameter = tipoMecanismoID.HasValue ?
                new ObjectParameter("TipoMecanismoID", tipoMecanismoID) :
                new ObjectParameter("TipoMecanismoID", typeof(short));
    
            var mecanismoIDParameter = mecanismoID.HasValue ?
                new ObjectParameter("MecanismoID", mecanismoID) :
                new ObjectParameter("MecanismoID", typeof(short));
    
            var partyIDParameter = partyID != null ?
                new ObjectParameter("PartyID", partyID) :
                new ObjectParameter("PartyID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_modificarMecanismo", valorMecanismoParameter, tipoMecanismoIDParameter, mecanismoIDParameter, partyIDParameter);
        }
    
        public virtual int p_modificarParty(string primerNombre, string segundoNombre, string apellido1, string apellido2, string contraseña, string partyID)
        {
            var primerNombreParameter = primerNombre != null ?
                new ObjectParameter("PrimerNombre", primerNombre) :
                new ObjectParameter("PrimerNombre", typeof(string));
    
            var segundoNombreParameter = segundoNombre != null ?
                new ObjectParameter("SegundoNombre", segundoNombre) :
                new ObjectParameter("SegundoNombre", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("Apellido1", apellido1) :
                new ObjectParameter("Apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("Apellido2", apellido2) :
                new ObjectParameter("Apellido2", typeof(string));
    
            var contraseñaParameter = contraseña != null ?
                new ObjectParameter("Contraseña", contraseña) :
                new ObjectParameter("Contraseña", typeof(string));
    
            var partyIDParameter = partyID != null ?
                new ObjectParameter("PartyID", partyID) :
                new ObjectParameter("PartyID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_modificarParty", primerNombreParameter, segundoNombreParameter, apellido1Parameter, apellido2Parameter, contraseñaParameter, partyIDParameter);
        }
    
        public virtual int p_modificarPlato(Nullable<int> platoID, string nombre, string descripcion, Nullable<decimal> precio, byte[] fotografia, Nullable<bool> habilitadoSN)
        {
            var platoIDParameter = platoID.HasValue ?
                new ObjectParameter("PlatoID", platoID) :
                new ObjectParameter("PlatoID", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(decimal));
    
            var fotografiaParameter = fotografia != null ?
                new ObjectParameter("Fotografia", fotografia) :
                new ObjectParameter("Fotografia", typeof(byte[]));
    
            var habilitadoSNParameter = habilitadoSN.HasValue ?
                new ObjectParameter("HabilitadoSN", habilitadoSN) :
                new ObjectParameter("HabilitadoSN", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_modificarPlato", platoIDParameter, nombreParameter, descripcionParameter, precioParameter, fotografiaParameter, habilitadoSNParameter);
        }
    
        public virtual int p_modificarUsuario(string partyID, Nullable<byte> tipoID)
        {
            var partyIDParameter = partyID != null ?
                new ObjectParameter("PartyID", partyID) :
                new ObjectParameter("PartyID", typeof(string));
    
            var tipoIDParameter = tipoID.HasValue ?
                new ObjectParameter("TipoID", tipoID) :
                new ObjectParameter("TipoID", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_modificarUsuario", partyIDParameter, tipoIDParameter);
        }
    
        public virtual int p_VerificarPedidos(Nullable<int> platoID, ObjectParameter pedidosPendientes)
        {
            var platoIDParameter = platoID.HasValue ?
                new ObjectParameter("PlatoID", platoID) :
                new ObjectParameter("PlatoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_VerificarPedidos", platoIDParameter, pedidosPendientes);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
