//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public byte DireccionID { get; set; }
        public string LineaDireccion1 { get; set; }
        public string LineaDireccion2 { get; set; }
        public string LineaDireccion3 { get; set; }
        public string Instrucciones { get; set; }
        public string PartyID { get; set; }
    
        public virtual Geo Geo { get; set; }
        public virtual Party Party { get; set; }
        public virtual TipoDireccion TipoDireccion { get; set; }
    }
}
