//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class MecanismoContacto
    {
        public short MecanismoID { get; set; }
        public short TipoMecanismoID { get; set; }
        public string Valor { get; set; }
        public string PartyID { get; set; }
    
        public virtual Party Party { get; set; }
        public virtual TipoMecanismo TipoMecanismo { get; set; }
    }
}
