//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class v_Pedido
{
    public int PedidoID { get; set; }
    public System.DateTime Fecha { get; set; }
    public byte EstadoID { get; set; }
    public string PartyID { get; set; }
}
